/*
 * This source file was generated by the Gradle 'init' task
 */
package exemploapigradle;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.URLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URI;
import java.nio.charset.Charset;

import com.google.gson.*;

public class App {

    public static void main(String[] args) {

        String sUrl = "https://reqres.in/api/users";
        // Connect to the URL using java's native library
        URL url;
        try {
            url = new URL(sUrl);

            URLConnection request = url.openConnection();
            request.connect();
            JsonElement root = JsonParser.parseReader(new InputStreamReader((InputStream) request.getContent())); //Convert the input stream to a json element
            JsonObject rootobj = root.getAsJsonObject(); //May be an array, may be an object. 

            System.out.println(rootobj);
            // String zipcode = rootobj.get("zip_code").getAsString(); //just grab the zipcode

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
}
