# Usa a imagem oficial do Node.js
FROM node:latest

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos do projeto para dentro do container
COPY code/ .

# Comando padrão ao executar o container
CMD ["node", "script.js"]