package com.example.labprog.crud;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(path="/users") // This means URL's start with /users (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    // C - Create
    @PostMapping(path="/create")
    public String addNewUser (@RequestParam String name, @RequestParam String email) {
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setFirstName(name);
        n.setEmail(email);
        userRepository.save(n);

        return "Saved";
    }

    @GetMapping(path="/all")
    public Iterable<User> getAllUsers() {
        return userRepository.findAll();
    }

    @GetMapping(path="/search/{name}")
    public Iterable<User> getUserByName(@PathVariable("name") String name) {
        
        return userRepository.findByFirstName(name);
    }
}