/*
 * This source file was generated by the Gradle 'init' task
 */
package exemplogradlearquivo;

import java.io.*; 
import java.util.*; 
import com.opencsv.*; 

public class App {

    static final String filePath = "MyFile.csv";

    public static void main(String[] args) {

        // Escrita
        List<String[]> data = new ArrayList<String[]>();
        data.add(new String[] { "Name", "Turma", "Nota" }); 
        data.add(new String[] { "João", "A", "9.0" }); 
        data.add(new String[] { "José", "B", "8.5" });
        
        writeToFile(data);

        // Leitura
        List<String[]> readData = readFromFile();

        for (String[] line : readData) {
            System.out.println(Arrays.toString(line));
        }
    }

    public static void writeToFile(List<String[]> data) {
        File file = new File(filePath); 
  
        try {
            FileWriter outputfile = new FileWriter(file);
            CSVWriter writer = new CSVWriter(outputfile);

            // Poderia usar: writer.writeAll(data);
            for(String[] line : data) {
                writer.writeNext(line);
            }
            writer.close(); 
        } 
        catch (IOException e) { 
            e.printStackTrace();
        } 
    }

    public static List<String[]> readFromFile() {
        List<String[]> data = new ArrayList<>();
        File file = new File(filePath);

        try {
            FileReader inputFile = new FileReader(file);
            CSVReader reader = new CSVReader(inputFile);

            String[] nextLine;
            while ((nextLine = reader.readNext()) != null) {
                data.add(nextLine);
            }

            reader.close();
        } 
        catch (IOException e) { 
            e.printStackTrace(); 
        }

        return data;
    }
}
